/* Generated by Yosys 0.58+35 (git sha1 9a12d92551096cd458fd635ed84acf3ba0f2c423, g++ 15.2.1 -O2 -flto=auto -ffat-lto-objects -fexceptions -fstack-protector-strong -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "src/ctrl_unit.v:1.1-403.10" *)
module ctrl_unit(clk, rst, opcode, func3, func7, branch_op, alu_valid, alu_op, DM_write_en, port_A_sel, port_B_sel, write_MUX_sel, PC_MUX_sel, imm_en, reg_write_en, branch_en, PC_stall, alu_en, reg_read_en, load_store_op, DM_read_en
);
  (* src = "src/ctrl_unit.v:5.13-5.16" *)
  input clk;
  wire clk;
  (* src = "src/ctrl_unit.v:5.18-5.21" *)
  input rst;
  wire rst;
  (* src = "src/ctrl_unit.v:6.27-6.33" *)
  input [6:0] opcode;
  wire [6:0] opcode;
  (* src = "src/ctrl_unit.v:7.27-7.32" *)
  input [3:0] func3;
  wire [3:0] func3;
  (* src = "src/ctrl_unit.v:8.27-8.32" *)
  input [6:0] func7;
  wire [6:0] func7;
  (* src = "src/ctrl_unit.v:10.27-10.36" *)
  input [2:0] branch_op;
  wire [2:0] branch_op;
  (* src = "src/ctrl_unit.v:11.27-11.36" *)
  input alu_valid;
  wire alu_valid;
  (* src = "src/ctrl_unit.v:13.33-13.39" *)
  output [5:0] alu_op;
  wire [5:0] alu_op;
  (* src = "src/ctrl_unit.v:16.27-16.38" *)
  output DM_write_en;
  wire DM_write_en;
  (* src = "src/ctrl_unit.v:17.27-17.37" *)
  output [1:0] port_A_sel;
  wire [1:0] port_A_sel;
  (* src = "src/ctrl_unit.v:18.27-18.37" *)
  output [1:0] port_B_sel;
  wire [1:0] port_B_sel;
  (* src = "src/ctrl_unit.v:19.27-19.40" *)
  output [1:0] write_MUX_sel;
  wire [1:0] write_MUX_sel;
  (* src = "src/ctrl_unit.v:20.27-20.37" *)
  output PC_MUX_sel;
  wire PC_MUX_sel;
  (* src = "src/ctrl_unit.v:21.27-21.33" *)
  output [1:0] imm_en;
  wire [1:0] imm_en;
  (* src = "src/ctrl_unit.v:22.27-22.39" *)
  output reg_write_en;
  wire reg_write_en;
  (* src = "src/ctrl_unit.v:23.27-23.36" *)
  output branch_en;
  wire branch_en;
  (* src = "src/ctrl_unit.v:24.27-24.35" *)
  output PC_stall;
  wire PC_stall;
  (* src = "src/ctrl_unit.v:25.27-25.33" *)
  output alu_en;
  wire alu_en;
  (* src = "src/ctrl_unit.v:26.27-26.38" *)
  output reg_read_en;
  wire reg_read_en;
  (* src = "src/ctrl_unit.v:27.27-27.40" *)
  output [2:0] load_store_op;
  wire [2:0] load_store_op;
  (* src = "src/ctrl_unit.v:28.27-28.37" *)
  output DM_read_en;
  wire DM_read_en;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  (* force_downto = 32'd1 *)
  (* src = "src/ctrl_unit.v:158.16-158.16|src/ctrl_unit.v:67.9-172.16|/usr/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire [5:0] _086_;
  (* force_downto = 32'd1 *)
  (* src = "src/ctrl_unit.v:158.16-158.16|src/ctrl_unit.v:67.9-172.16|/usr/bin/../share/yosys/techmap.v:583.21-583.22" *)
  (* unused_bits = "1 2 5" *)
  wire [5:0] _087_;
  (* nosync = 32'd1 *)
  (* src = "src/ctrl_unit.v:369.14-369.20" *)
  wire \func3_B$func$src/ctrl_unit.v:138$5.branch ;
  (* nosync = 32'd1 *)
  (* src = "src/ctrl_unit.v:367.19-367.25" *)
  wire [2:0] \func3_B$func$src/ctrl_unit.v:138$5.func_3 ;
  (* nosync = 32'd1 *)
  (* src = "src/ctrl_unit.v:268.26-268.32" *)
  wire [3:0] \func3_I_A$func$src/ctrl_unit.v:90$2.func_3 ;
  (* nosync = 32'd1 *)
  (* src = "src/ctrl_unit.v:269.19-269.25" *)
  wire [6:0] \func3_I_A$func$src/ctrl_unit.v:90$2.func_7 ;
  (* nosync = 32'd1 *)
  (* src = "src/ctrl_unit.v:271.27-271.36" *)
  wire [5:0] \func3_I_A$func$src/ctrl_unit.v:90$2.operation ;
  (* nosync = 32'd1 *)
  (* src = "src/ctrl_unit.v:314.26-314.32" *)
  wire [3:0] \func3_I_L$func$src/ctrl_unit.v:102$3.func_3 ;
  (* nosync = 32'd1 *)
  (* src = "src/ctrl_unit.v:316.27-316.36" *)
  wire [5:0] \func3_I_L$func$src/ctrl_unit.v:102$3.operation ;
  (* nosync = 32'd1 *)
  (* src = "src/ctrl_unit.v:218.26-218.32" *)
  wire [3:0] \func3_R$func$src/ctrl_unit.v:76$1.func_3 ;
  (* nosync = 32'd1 *)
  (* src = "src/ctrl_unit.v:219.19-219.25" *)
  wire [6:0] \func3_R$func$src/ctrl_unit.v:76$1.func_7 ;
  (* nosync = 32'd1 *)
  (* src = "src/ctrl_unit.v:221.27-221.36" *)
  wire [5:0] \func3_R$func$src/ctrl_unit.v:76$1.operation ;
  (* nosync = 32'd1 *)
  (* src = "src/ctrl_unit.v:344.26-344.32" *)
  wire [3:0] \func3_S$func$src/ctrl_unit.v:124$4.func_3 ;
  (* nosync = 32'd1 *)
  (* src = "src/ctrl_unit.v:346.27-346.36" *)
  wire [2:0] \func3_S$func$src/ctrl_unit.v:124$4.operation ;
  (* src = "src/ctrl_unit.v:46.15-46.24" *)
  wire [5:0] inst_type;
  (* src = "src/ctrl_unit.v:37.15-37.20" *)
  wire [4:0] state;
  sky130_fd_sc_hd__clkinv_1 _088_ (
    .A(state[1]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__clkinv_1 _089_ (
    .A(opcode[5]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nor2_1 _090_ (
    .A(state[3]),
    .B(state[2]),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nor3_1 _091_ (
    .A(state[4]),
    .B(state[3]),
    .C(state[2]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__a31oi_1 _092_ (
    .A1(_054_),
    .A2(state[0]),
    .A3(_057_),
    .B1(rst),
    .Y(_058_)
  );
  sky130_fd_sc_hd__a31o_1 _093_ (
    .A1(_054_),
    .A2(state[0]),
    .A3(_057_),
    .B1(rst),
    .X(_059_)
  );
  sky130_fd_sc_hd__or3_1 _094_ (
    .A(state[4]),
    .B(state[1]),
    .C(state[0]),
    .X(_060_)
  );
  sky130_fd_sc_hd__nand2b_1 _095_ (
    .A_N(state[2]),
    .B(state[3]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nor2_1 _096_ (
    .A(_060_),
    .B(_061_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__o21ai_0 _097_ (
    .A1(DM_write_en),
    .A2(_062_),
    .B1(_058_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand2b_1 _098_ (
    .A_N(opcode[4]),
    .B(opcode[5]),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand4bb_1 _099_ (
    .A_N(opcode[2]),
    .B_N(opcode[3]),
    .C(opcode[0]),
    .D(opcode[1]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nor2_1 _100_ (
    .A(opcode[6]),
    .B(_065_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _101_ (
    .A(opcode[6]),
    .SLEEP(_065_),
    .X(_067_)
  );
  sky130_fd_sc_hd__nor3_1 _102_ (
    .A(opcode[6]),
    .B(_064_),
    .C(_065_),
    .Y(_086_[2])
  );
  sky130_fd_sc_hd__nor3b_1 _103_ (
    .A(_054_),
    .B(state[0]),
    .C_N(_057_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _104_ (
    .A(_068_),
    .SLEEP(rst),
    .X(_069_)
  );
  sky130_fd_sc_hd__nand2_1 _105_ (
    .A(_086_[2]),
    .B(_069_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nand2_1 _106_ (
    .A(_063_),
    .B(_070_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__o211ai_1 _107_ (
    .A1(opcode[5]),
    .A2(opcode[4]),
    .B1(_066_),
    .C1(_069_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nand3b_1 _108_ (
    .A_N(opcode[4]),
    .B(opcode[6]),
    .C(opcode[5]),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nor2_1 _109_ (
    .A(_065_),
    .B(_072_),
    .Y(_086_[3])
  );
  sky130_fd_sc_hd__and2_0 _110_ (
    .A(_068_),
    .B(_086_[3]),
    .X(_073_)
  );
  sky130_fd_sc_hd__nand4_1 _111_ (
    .A(opcode[1]),
    .B(opcode[2]),
    .C(opcode[3]),
    .D(opcode[0]),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nor2_1 _112_ (
    .A(_072_),
    .B(_074_),
    .Y(_087_[0])
  );
  sky130_fd_sc_hd__a21oi_1 _113_ (
    .A1(_065_),
    .A2(_074_),
    .B1(_072_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__o21ai_0 _114_ (
    .A1(_066_),
    .A2(_075_),
    .B1(_068_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__o21a_1 _115_ (
    .A1(_066_),
    .A2(_075_),
    .B1(_068_),
    .X(_077_)
  );
  sky130_fd_sc_hd__nand3_1 _116_ (
    .A(port_A_sel[0]),
    .B(_058_),
    .C(_076_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nand2_1 _117_ (
    .A(_071_),
    .B(_078_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__o21ai_0 _118_ (
    .A1(port_A_sel[1]),
    .A2(_077_),
    .B1(_058_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nor3_1 _119_ (
    .A(_086_[2]),
    .B(_075_),
    .C(_076_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nor2_1 _120_ (
    .A(_079_),
    .B(_080_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nor3_1 _121_ (
    .A(opcode[5]),
    .B(opcode[6]),
    .C(_065_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nor2_1 _122_ (
    .A(_075_),
    .B(_081_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__o21ai_0 _123_ (
    .A1(port_B_sel[0]),
    .A2(_077_),
    .B1(_058_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__a21oi_1 _124_ (
    .A1(_077_),
    .A2(_082_),
    .B1(_083_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__and3_1 _125_ (
    .A(port_B_sel[1]),
    .B(_058_),
    .C(_076_),
    .X(_006_)
  );
  sky130_fd_sc_hd__or3_1 _126_ (
    .A(inst_type[5]),
    .B(inst_type[4]),
    .C(inst_type[3]),
    .X(_084_)
  );
  sky130_fd_sc_hd__nor2_1 _127_ (
    .A(inst_type[1]),
    .B(inst_type[0]),
    .Y(_085_)
  );
  sky130_fd_sc_hd__a21o_1 _128_ (
    .A1(inst_type[1]),
    .A2(inst_type[0]),
    .B1(inst_type[2]),
    .X(_019_)
  );
  sky130_fd_sc_hd__nor3_1 _129_ (
    .A(_084_),
    .B(_085_),
    .C(_019_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nor3b_1 _130_ (
    .A(_060_),
    .B(state[3]),
    .C_N(state[2]),
    .Y(_021_)
  );
  sky130_fd_sc_hd__and3_1 _131_ (
    .A(alu_valid),
    .B(_020_),
    .C(_021_),
    .X(_022_)
  );
  sky130_fd_sc_hd__nor2_1 _132_ (
    .A(write_MUX_sel[0]),
    .B(_022_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nor2_1 _133_ (
    .A(_059_),
    .B(_023_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__o21ai_0 _134_ (
    .A1(_087_[0]),
    .A2(_081_),
    .B1(_069_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__o31ai_1 _135_ (
    .A1(_086_[2]),
    .A2(_087_[0]),
    .A3(_081_),
    .B1(_068_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nand3_1 _136_ (
    .A(imm_en[0]),
    .B(_058_),
    .C(_025_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nand2_1 _137_ (
    .A(_024_),
    .B(_026_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nand3_1 _138_ (
    .A(imm_en[1]),
    .B(_058_),
    .C(_025_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__o21ai_0 _139_ (
    .A1(_086_[2]),
    .A2(_087_[0]),
    .B1(_069_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2_1 _140_ (
    .A(_027_),
    .B(_028_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nor3b_1 _141_ (
    .A(state[1]),
    .B(state[0]),
    .C_N(state[4]),
    .Y(_029_)
  );
  sky130_fd_sc_hd__a21oi_1 _142_ (
    .A1(_056_),
    .A2(_029_),
    .B1(reg_write_en),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nor2_1 _143_ (
    .A(_059_),
    .B(_030_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nor2_1 _144_ (
    .A(branch_en),
    .B(_073_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nor2_1 _145_ (
    .A(_059_),
    .B(_031_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__o21ai_0 _146_ (
    .A1(alu_en),
    .A2(_021_),
    .B1(_058_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__a21oi_1 _147_ (
    .A1(alu_valid),
    .A2(_021_),
    .B1(_032_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__o21ai_0 _148_ (
    .A1(reg_read_en),
    .A2(_073_),
    .B1(_058_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _149_ (
    .A(_071_),
    .B(_033_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__a21oi_1 _150_ (
    .A1(inst_type[5]),
    .A2(inst_type[4]),
    .B1(inst_type[2]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__o21ai_0 _151_ (
    .A1(inst_type[5]),
    .A2(inst_type[4]),
    .B1(inst_type[3]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__and4_1 _152_ (
    .A(_084_),
    .B(_085_),
    .C(_034_),
    .D(_035_),
    .X(_036_)
  );
  sky130_fd_sc_hd__a2bb2o_1 _153_ (
    .A1_N(_060_),
    .A2_N(_061_),
    .B1(_029_),
    .B2(_056_),
    .X(_037_)
  );
  sky130_fd_sc_hd__a311oi_1 _154_ (
    .A1(alu_valid),
    .A2(_021_),
    .A3(_036_),
    .B1(_037_),
    .C1(state[0]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nor2_1 _155_ (
    .A(_059_),
    .B(_038_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nor2_1 _156_ (
    .A(_021_),
    .B(_037_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand4b_1 _157_ (
    .A_N(opcode[3]),
    .B(opcode[0]),
    .C(opcode[1]),
    .D(opcode[2]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand2b_1 _158_ (
    .A_N(opcode[6]),
    .B(opcode[4]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nor2_1 _159_ (
    .A(_040_),
    .B(_041_),
    .Y(_086_[4])
  );
  sky130_fd_sc_hd__a21oi_1 _160_ (
    .A1(_072_),
    .A2(_041_),
    .B1(_040_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__o31ai_1 _161_ (
    .A1(_066_),
    .A2(_087_[0]),
    .A3(_042_),
    .B1(_068_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__o31ai_1 _162_ (
    .A1(_066_),
    .A2(_075_),
    .A3(_042_),
    .B1(_068_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nand3_1 _163_ (
    .A(state[1]),
    .B(_039_),
    .C(_044_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand2_1 _164_ (
    .A(_058_),
    .B(_045_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nand3_1 _165_ (
    .A(state[2]),
    .B(_039_),
    .C(_044_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nor4b_1 _166_ (
    .A(inst_type[1]),
    .B(_084_),
    .C(inst_type[0]),
    .D_N(inst_type[2]),
    .Y(_047_)
  );
  sky130_fd_sc_hd__o31ai_1 _167_ (
    .A1(_020_),
    .A2(_036_),
    .A3(_047_),
    .B1(alu_valid),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand2_1 _168_ (
    .A(_021_),
    .B(_048_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__a31oi_1 _169_ (
    .A1(_043_),
    .A2(_046_),
    .A3(_049_),
    .B1(_059_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nand3_1 _170_ (
    .A(state[3]),
    .B(_039_),
    .C(_044_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nand3_1 _171_ (
    .A(alu_valid),
    .B(_021_),
    .C(_047_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__a21oi_1 _172_ (
    .A1(_050_),
    .A2(_051_),
    .B1(_059_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__a31oi_1 _173_ (
    .A1(state[4]),
    .A2(_039_),
    .A3(_044_),
    .B1(_022_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nor2_1 _174_ (
    .A(_059_),
    .B(_052_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__a21oi_1 _175_ (
    .A1(_064_),
    .A2(_066_),
    .B1(_087_[0]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _176_ (
    .A(_069_),
    .SLEEP(_053_),
    .X(_001_)
  );
  sky130_fd_sc_hd__nor2_1 _177_ (
    .A(_059_),
    .B(_044_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nor3_1 _178_ (
    .A(opcode[5]),
    .B(opcode[4]),
    .C(_067_),
    .Y(_087_[4])
  );
  sky130_fd_sc_hd__nor3_1 _179_ (
    .A(_055_),
    .B(_065_),
    .C(_041_),
    .Y(_086_[0])
  );
  sky130_fd_sc_hd__o22ai_1 _180_ (
    .A1(opcode[5]),
    .A2(_067_),
    .B1(_072_),
    .B2(_040_),
    .Y(_086_[1])
  );
  sky130_fd_sc_hd__nor2_1 _181_ (
    .A(_072_),
    .B(_074_),
    .Y(_086_[5])
  );
  (* src = "src/ctrl_unit.v:50.5-212.8" *)
  sky130_fd_sc_hd__edfxtp_1 _182_ (
    .CLK(clk),
    .D(_087_[0]),
    .DE(_001_),
    .Q(alu_op[0])
  );
  (* src = "src/ctrl_unit.v:50.5-212.8" *)
  sky130_fd_sc_hd__edfxtp_1 _183_ (
    .CLK(clk),
    .D(_087_[4]),
    .DE(_001_),
    .Q(alu_op[4])
  );
  (* src = "src/ctrl_unit.v:50.5-212.8" *)
  sky130_fd_sc_hd__dfxtp_1 _184_ (
    .CLK(clk),
    .D(_002_),
    .Q(DM_write_en)
  );
  (* src = "src/ctrl_unit.v:50.5-212.8" *)
  sky130_fd_sc_hd__dfxtp_1 _185_ (
    .CLK(clk),
    .D(_003_),
    .Q(port_A_sel[0])
  );
  (* src = "src/ctrl_unit.v:50.5-212.8" *)
  sky130_fd_sc_hd__dfxtp_1 _186_ (
    .CLK(clk),
    .D(_004_),
    .Q(port_A_sel[1])
  );
  (* src = "src/ctrl_unit.v:50.5-212.8" *)
  sky130_fd_sc_hd__dfxtp_1 _187_ (
    .CLK(clk),
    .D(_005_),
    .Q(port_B_sel[0])
  );
  (* src = "src/ctrl_unit.v:50.5-212.8" *)
  sky130_fd_sc_hd__dfxtp_1 _188_ (
    .CLK(clk),
    .D(_006_),
    .Q(port_B_sel[1])
  );
  (* src = "src/ctrl_unit.v:50.5-212.8" *)
  sky130_fd_sc_hd__dfxtp_1 _189_ (
    .CLK(clk),
    .D(_007_),
    .Q(write_MUX_sel[0])
  );
  (* src = "src/ctrl_unit.v:50.5-212.8" *)
  sky130_fd_sc_hd__dfxtp_1 _190_ (
    .CLK(clk),
    .D(_008_),
    .Q(imm_en[0])
  );
  (* src = "src/ctrl_unit.v:50.5-212.8" *)
  sky130_fd_sc_hd__dfxtp_1 _191_ (
    .CLK(clk),
    .D(_009_),
    .Q(imm_en[1])
  );
  (* src = "src/ctrl_unit.v:50.5-212.8" *)
  sky130_fd_sc_hd__dfxtp_1 _192_ (
    .CLK(clk),
    .D(_010_),
    .Q(reg_write_en)
  );
  (* src = "src/ctrl_unit.v:50.5-212.8" *)
  sky130_fd_sc_hd__dfxtp_1 _193_ (
    .CLK(clk),
    .D(_011_),
    .Q(branch_en)
  );
  (* src = "src/ctrl_unit.v:50.5-212.8" *)
  sky130_fd_sc_hd__dfxtp_1 _194_ (
    .CLK(clk),
    .D(_012_),
    .Q(alu_en)
  );
  (* src = "src/ctrl_unit.v:50.5-212.8" *)
  sky130_fd_sc_hd__dfxtp_1 _195_ (
    .CLK(clk),
    .D(_013_),
    .Q(reg_read_en)
  );
  (* src = "src/ctrl_unit.v:50.5-212.8" *)
  sky130_fd_sc_hd__dfxtp_1 _196_ (
    .CLK(clk),
    .D(_014_),
    .Q(state[0])
  );
  (* src = "src/ctrl_unit.v:50.5-212.8" *)
  sky130_fd_sc_hd__dfxtp_1 _197_ (
    .CLK(clk),
    .D(_015_),
    .Q(state[1])
  );
  (* src = "src/ctrl_unit.v:50.5-212.8" *)
  sky130_fd_sc_hd__dfxtp_1 _198_ (
    .CLK(clk),
    .D(_016_),
    .Q(state[2])
  );
  (* src = "src/ctrl_unit.v:50.5-212.8" *)
  sky130_fd_sc_hd__dfxtp_1 _199_ (
    .CLK(clk),
    .D(_017_),
    .Q(state[3])
  );
  (* src = "src/ctrl_unit.v:50.5-212.8" *)
  sky130_fd_sc_hd__dfxtp_1 _200_ (
    .CLK(clk),
    .D(_018_),
    .Q(state[4])
  );
  (* src = "src/ctrl_unit.v:50.5-212.8" *)
  sky130_fd_sc_hd__edfxtp_1 _201_ (
    .CLK(clk),
    .D(_086_[0]),
    .DE(_000_),
    .Q(inst_type[0])
  );
  (* src = "src/ctrl_unit.v:50.5-212.8" *)
  sky130_fd_sc_hd__edfxtp_1 _202_ (
    .CLK(clk),
    .D(_086_[1]),
    .DE(_000_),
    .Q(inst_type[1])
  );
  (* src = "src/ctrl_unit.v:50.5-212.8" *)
  sky130_fd_sc_hd__edfxtp_1 _203_ (
    .CLK(clk),
    .D(_086_[2]),
    .DE(_000_),
    .Q(inst_type[2])
  );
  (* src = "src/ctrl_unit.v:50.5-212.8" *)
  sky130_fd_sc_hd__edfxtp_1 _204_ (
    .CLK(clk),
    .D(_086_[3]),
    .DE(_000_),
    .Q(inst_type[3])
  );
  (* src = "src/ctrl_unit.v:50.5-212.8" *)
  sky130_fd_sc_hd__edfxtp_1 _205_ (
    .CLK(clk),
    .D(_086_[4]),
    .DE(_000_),
    .Q(inst_type[4])
  );
  (* src = "src/ctrl_unit.v:50.5-212.8" *)
  sky130_fd_sc_hd__edfxtp_1 _206_ (
    .CLK(clk),
    .D(_086_[5]),
    .DE(_000_),
    .Q(inst_type[5])
  );
  assign _087_[3:1] = { _087_[4], _087_[5], _087_[5] };
  assign { alu_op[5], alu_op[3:1] } = { 1'h0, alu_op[4], 2'h0 };
  assign \func3_B$func$src/ctrl_unit.v:138$5.branch  = 1'hx;
  assign \func3_B$func$src/ctrl_unit.v:138$5.func_3  = 3'hx;
  assign \func3_I_A$func$src/ctrl_unit.v:90$2.func_3  = 4'hx;
  assign \func3_I_A$func$src/ctrl_unit.v:90$2.func_7  = 7'hxx;
  assign \func3_I_A$func$src/ctrl_unit.v:90$2.operation  = 6'hxx;
  assign \func3_I_L$func$src/ctrl_unit.v:102$3.func_3  = 4'hx;
  assign \func3_I_L$func$src/ctrl_unit.v:102$3.operation  = 6'hxx;
  assign \func3_R$func$src/ctrl_unit.v:76$1.func_3  = 4'hx;
  assign \func3_R$func$src/ctrl_unit.v:76$1.func_7  = 7'hxx;
  assign \func3_R$func$src/ctrl_unit.v:76$1.operation  = 6'hxx;
  assign \func3_S$func$src/ctrl_unit.v:124$4.func_3  = 4'hx;
  assign \func3_S$func$src/ctrl_unit.v:124$4.operation  = 3'hx;
  assign load_store_op = 3'h0;
  assign write_MUX_sel[1] = write_MUX_sel[0];
endmodule
